trigger:
- main

pool:
  name: AzurePoolAgent

steps:

- task: Docker@2
  inputs:
    command: build
    Dockerfile: Dockerfile
    tags: devops-demo

- script: |
    kubectl apply -f deployment.yaml
    kubectl apply -f service.yaml
  displayName: Deploy to Kubernetes